name: Checkout 
on: [push]
jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout 
        run: ls -a
      - uses: actions/checkout@v3
      - name: List File After Checkout 
        run: ls -a
